theme: jekyll-theme-minimal
title: Alexander Kell
description: Researcher in complex systems.
logo: https://github.com/alexanderkell/alexanderkell.github.io/blob/main/13176011.jpeg?raw=true
google_analytics: G-VJTQS3Q02B
